<a href="https://colab.research.google.com/github/RobSpiewakowski/Public_repository/blob/main/SDS_Modu%C5%82_5_Praca_domowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modul 5 - Praca domowa - Python

Zwykle istnieje wiele sposobów, żeby rozwiązać zadanie w Python. Także czasami warto spróbować opracować kod na 1-2 sposoby :)

## Zadanie - 1

Utwórz macierze a także przeprowadź na nich obliczenia. Postępuj wg. kroków:
* ustaw ziarno losowości równe `5` wykorzystując funkcję dostępną w bibliotece `numpy`;
* wygeneruj 2 ciągi liczb całkowitych z zakresu od 1 do 100. Określ liczbę elementów 20 i 32 odpowiednio. Do tego możesz użyć funkcji: `np.random.randint()`;
* wykorzystaj wygenerowane liczby aby stworzyć macierze `5x4` i `4x8` odpowiednio;
* wykonaj mnożenie stworzonych macierzy;
* podnieś wszystkie elementy macierzy wynikowej z poprzedniego kroku do potęgi `2`;
* odejmij wartość minimalną od każdego elementu macierzy z poprzedniego kroku;
* wylicz sumę wszystkich elementów macierzy;

In [17]:
import random
import numpy as np
import plotly.express as px
import pandas as pd
random_state = 5

In [3]:
# Wygenerowanie ciągów:
A = np.random.randint(0, 100, 20)
B = np.random.randint(0, 100, 32)

In [11]:
# Nadanie kształtu macierzom:
A = A.reshape(5, 4)
B = B.reshape(4, 8)

print('A  =', '\n', A, '\n', '----------------------------', '\n', 'B = ', '\n', B)

A  = 
 [[57  5 74  9]
 [58 15 88 20]
 [10 16 12 18]
 [56 27 38 64]
 [55 22  9 67]] 
 ---------------------------- 
 B =  
 [[39 94 35 60  3 65 45 42]
 [11  8 48 42 82 96 60 42]
 [83 29 45  3 25 60 92 76]
 [76  9 37 50 62 92 72 91]]


In [12]:
# Mnożenie macierzy:
C = np.dot(A, B)
print('C = ', '\n', C)

C =  
 [[ 9104  7625  5898  4302  2989  9453 10321  9047]
 [11251  8304  7450  5374  4844 12330 13046 11574]
 [ 2930  1578  2324  2208  2758  4562  3810  3642]
 [10499  7158  7334  7808  7300 14400 12244 12198]
 [ 8226  6210  5865  7601  6348 12391  9447 10015]]


In [13]:
# Podnieś wszystkie elementy macierzy wynikowej do kwadratu:
C2 = C**2
print('C2 = ', '\n', C2)

C2 =  
 [[ 82882816  58140625  34786404  18507204   8934121  89359209 106523041
   81848209]
 [126585001  68956416  55502500  28879876  23464336 152028900 170198116
  133957476]
 [  8584900   2490084   5400976   4875264   7606564  20811844  14516100
   13264164]
 [110229001  51236964  53787556  60964864  53290000 207360000 149915536
  148791204]
 [ 67667076  38564100  34398225  57775201  40297104 153536881  89245809
  100300225]]


In [14]:
# odejmij wartość minimalną od każdego elementu macierzy z poprzedniego kroku
D = C2 - C2.min()
print('D = ', '\n', D)

D =  
 [[ 80392732  55650541  32296320  16017120   6444037  86869125 104032957
   79358125]
 [124094917  66466332  53012416  26389792  20974252 149538816 167708032
  131467392]
 [  6094816         0   2910892   2385180   5116480  18321760  12026016
   10774080]
 [107738917  48746880  51297472  58474780  50799916 204869916 147425452
  146301120]
 [ 65176992  36074016  31908141  55285117  37807020 151046797  86755725
   97810141]]


In [15]:
# wylicz sumę wszystkich elementów macierzy:
print(D.sum())

2635860532


## Zadanie - 2

Wykorzystaj podejście statystyki opisowej do [Zbioru Danych](https://bit.ly/2XXZo2R) o ocenie czerwonego wina aby odpowiedzieć na kolejne pytania:
* jak wyglądają podstawowe statystyki dotyczace zbioru danych?
* jak wygląda rozkład dla poszczególnych kolumn? 
* jakie są średnie charakterystyki najlepszego wina?
* jakie są średnie charakterystyki najgorszego wina?
* czy mocniejsze wino ma lepsze oceny?
* jakie zależności widać w danych?
* jakie cechy w największym stopniu wpływają na ocenę czerwonego wina?


In [19]:
# Pobranie i prezentacja danych:
dane = pd.read_csv('/content/wineQualityReds.csv')
dane.head(10)

Unnamed: 0  fixed.acidity  volatile.acidity  ...  sulphates  alcohol  quality
0           1            7.4              0.70  ...       0.56      9.4        5
1           2            7.8              0.88  ...       0.68      9.8        5
2           3            7.8              0.76  ...       0.65      9.8        5
3           4           11.2              0.28  ...       0.58      9.8        6
4           5            7.4              0.70  ...       0.56      9.4        5
5           6            7.4              0.66  ...       0.56      9.4        5
6           7            7.9              0.60  ...       0.46      9.4        5
7           8            7.3              0.65  ...       0.47     10.0        7
8           9            7.8              0.58  ...       0.57      9.5        7
9          10            7.5              0.50  ...       0.80     10.5        5

[10 rows x 13 columns]

In [20]:
# Podstawowa analiza danych:
dane.describe()

Unnamed: 0  fixed.acidity  ...      alcohol      quality
count  1599.000000    1599.000000  ...  1599.000000  1599.000000
mean    800.000000       8.319637  ...    10.422983     5.636023
std     461.735855       1.741096  ...     1.065668     0.807569
min       1.000000       4.600000  ...     8.400000     3.000000
25%     400.500000       7.100000  ...     9.500000     5.000000
50%     800.000000       7.900000  ...    10.200000     6.000000
75%    1199.500000       9.200000  ...    11.100000     6.000000
max    1599.000000      15.900000  ...    14.900000     8.000000

[8 rows x 13 columns]

In [22]:
# Wykresy rozkładu poszczególnych zmiennych:
cechy = ["fixed.acidity",
         "volatile.acidity",
         "citric.acid",
         "residual.sugar",
         "chlorides",
         "free.sulfur.dioxide",
         "total.sulfur.dioxide",
         "density",
         "pH",
         "sulphates",
         "alcohol",
         "quality"]

for i in range(len(cechy)):
  hist = px.histogram(dane, x = cechy[i], title = f'Wykres rozkładu zmiennej - {cechy[i]}')
  hist.show()

In [27]:
# Jakie są średnie charakterystyki najlepszego wina:
top_wine = dane[dane['quality'] ==  max(dane['quality'].values)]

print('Liczba najlepiej ocenionych win:', {top_wine['pH'].count()})
print('Średni woltaż najlepiej ocenionych win:', {top_wine['alcohol'].mean()})
print('Średnie pH najlepiej ocenionych win:', {top_wine['pH'].mean()})

Liczba najlepiej ocenionych win: {18}
Średni woltaż najlepiej ocenionych win: {12.094444444444443}
Średnie pH najlepiej ocenionych win: {3.2672222222222214}


In [28]:
# Jakie są średnie charakterystyki najgorszego wina:
bottom_wine = dane[dane['quality'] ==  min(dane['quality'].values)]

print('Liczba najlepiej ocenionych win:', {bottom_wine['pH'].count()})
print('Średni woltaż najlepiej ocenionych win:', {bottom_wine['alcohol'].mean()})
print('Średnie pH najlepiej ocenionych win:', {bottom_wine['pH'].mean()})

Liczba najlepiej ocenionych win: {10}
Średni woltaż najlepiej ocenionych win: {9.955000000000002}
Średnie pH najlepiej ocenionych win: {3.3979999999999997}


In [29]:
# Czy modniejsze wino jest lepiej oceniane?
# Sprawdzamy korelację między zmiennymi alcohol i quality:
dane[['alcohol', 'quality']].corr().style.background_gradient(cmap = 'RdBu_r')

# Odp. Nie.

In [31]:
# Jakie jeszcze zależności widać na danych?

dane.corr().style.background_gradient(cmap = 'RdBu_r')