<a href="https://colab.research.google.com/github/RobSpiewakowski/nauka-data-science/blob/main/skrypty-colab/UDEMY_%C4%86wiczenia_z_uczenia_maszynowego.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Import modułów:
import sklearn as sl
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

# Ćwiczenie 1

Z poniższego słoenika utwórz obiekt Data Frame i przypisz go do zmiennej df. Następnie zapoznaj się z obiektem df i sprawdź liczbę braków danych dla wszystkich kolumn. Podaj procent braków, wynik zaokrąglij do drugiego miejsca po przecinku i wydrukuj na konsoli.

In [ ]:
# Dane:
data = {'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']}

df = pd.DataFrame(data)

# Zaokrąglony do 2 miejsc po przecinku, wynik dzielenia sumy wszystkich pustych komórek przez liczbę wszystkich komórek w kolumnie.
print(np.round(df.isnull().sum() / len(df), 2))

# Wyświetlenie Data Frame
df

size      0.17
color     0.00
gender    0.17
price     0.17
weight    0.33
bought    0.00
dtype: float64


size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

# Ćwiczenie 2. 

Dany jest obiekt Data Frame (jak w poprzednim ćwiczeniu). Za pomocą pakietu scikit-learn oraz klasy SimpleImputer uzupełnij braki danych dla kolumny "weight" wartościami średnimi. Zmiany przypisz do obiektu df. Wydrukuj obiekt df.

In [ ]:
# Utworzenie imputera (funkcji uzupełniającej braki):
imp_mean = SimpleImputer(missing_values = np.NaN, strategy = "mean")

# Wytrenowanie imputera:
imp_mean.fit(df[["weight"]])

# Zastosowanie imputera:
df["weight"] = imp_mean.transform(df[["weight"]])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

# Ćwiczenie 3.

Dany jest obiekt Data Frame (jak w poprzednim zadaniu). Braki danych dla kolumny "weight" zostały uzupełnione wartością średnią za pomocą klasy SimpleImputer. Wyświetl tę wartość średnią wykorzystując klasę SimpleImputer.

In [ ]:
# Wyświetla wartość wygenerowaną przez SimpleImputer:
print(imp_mean.statistics_)

[415.]


# Ćwiczenie 4

Jest dany obiekt Data Frame (nie zgadniesz, który...). Wykorzystując pakiet do uczenia maszynowego scikit-learn i klasę SimpleImputer, uzupełnij braki danych w kolumnie "price" stałą wartością 99.0. Zmiany przypisz na stałe do obiektu df.

In [ ]:
# Utworzenie imputera:
imp_const = SimpleImputer(missing_values = np.NaN, strategy = "constant", fill_value = 99.0)

# Wytrenowanie imnputera:
imp_const.fit(df[["price"]])

# Zastosowanie imputera:
df["price"] = imp_const.transform(df[["price"]])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN   99.0   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

# Ćwiczenie 5

Poniżej dany jest obiekt Data Frame (ten, co zwykle). Kosrzystając z pakietu scikit-learn oraz klast SimpleImputer, uzupełnij braki danych w kolumnie "size" najczęściej pojawiającą się wartością. zmiany przypisz na stałe do obiektu df.

In [ ]:
# Utworzenie imputera:
imp_mfreq = SimpleImputer(missing_values = np.NaN, strategy = "most_frequent")

# Wytrenowanie imputera:
imp_mfreq.fit(df[["size"]])

# Użycie imputera:
df["size"] = imp_mfreq.transform(df[["size"]])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN   99.0   300.0    yes
3    M  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

# Ćwiczenie 6

Dany jest obiekt Data Frame. Wytnij wszystkie wiersze, w których kolumna "weight" nie przyjmuje wartości NAN i policz średnią wartość dla kolumn numerycznych.

In [ ]:
# Trzeba przywrócić wartość NAN:
df["weight"][3] = np.NAN

# Wywołanie średnich wszystkich kolumn, w których "weight" nie jest nieznana:
print(df[~df["weight"].isnull()].mean())

price     111.0
weight    415.0
dtype: float64


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


# Ćwiczenie 7

Z obiektu Data Frame wydobądź kolumny typu "object". Następnie wszystkie braki danych uzupełnij wartością "empty". Wynik przypisz do zmiennej df.

In [ ]:
# Wygenerowanie nowego df ze zmienionymi danymi:
df_empty = df.select_dtypes(include = ["object"]).fillna("empty")
df_empty

size  color  gender bought
0   XL    red  female    yes
1    L  green    male     no
2    M   blue   empty    yes
3    M  green  female     no
4    M    red  female    yes
5    M  green    male     no

# Ćwiczenie 8

Dany jest obiekt Data Frame (poniżej). Dokonaj dyskretyzacji danych na 3 przedziały o równej szerokości. Przypisz wynik do kolumny o nazwie "weight_cut" i wydrukuj obiekt df na konsoli.

In [ ]:
# Utworzenie Data Frame:
df = pd.DataFrame(data = {'weight' : [75., 78.5, 85., 91., 84.5, 83., 68.]})

# Utworzenie przedziałów za pomocą funkcji pd.cut():
df['weight_cut'] = pd.cut(df['weight'], bins = 3)
df

weight        weight_cut
0    75.0  (67.977, 75.667]
1    78.5  (75.667, 83.333]
2    85.0    (83.333, 91.0]
3    91.0    (83.333, 91.0]
4    84.5    (83.333, 91.0]
5    83.0  (75.667, 83.333]
6    68.0  (67.977, 75.667]

# Ćwiczenie 9

Dany jest obiekt Data Frame (tak, jak w poprzednim zadaniu). Dokonaj dyskretyzacji kolumny "weight" na 3 przedziały o zadanej postaci:
* (60, 75],
* (75, 80],
* (80, 95].

Wynik przypisz do zmiennej 'weight_cut' i pokaż df.

In [ ]:
# Utworzenie Data Frame:
df = pd.DataFrame(data = {'weight' : [75., 78.5, 85., 91., 84.5, 83., 68.]})

# Utworzenie przedziałów za pomocą funkcji pd.cut():
df['weight_cut'] = pd.cut(df['weight'], bins = (60, 75, 80, 95))
df

weight weight_cut
0    75.0   (60, 75]
1    78.5   (75, 80]
2    85.0   (80, 95]
3    91.0   (80, 95]
4    84.5   (80, 95]
5    83.0   (80, 95]
6    68.0   (60, 75]

# Ćwiczenie 10

Dany jest znów ten sam Data Frame. Tym razem dokonaj dyskretyzacji kolumny na te same przedziały, ale dodaj im etykietkę: light, medium, heavy.

In [ ]:
# Utworzenie Data Frame:
df = pd.DataFrame(data = {'weight' : [75., 78.5, 85., 91., 84.5, 83., 68.]})

# Utworzenie przedziałów za pomocą funkcji pd.cut():
df['weight_cut'] = pd.cut(df['weight'], bins = (60, 75, 80, 95), labels = ("light", "medium", "heavy"))
df

weight weight_cut
0    75.0      light
1    78.5     medium
2    85.0      heavy
3    91.0      heavy
4    84.5      heavy
5    83.0      heavy
6    68.0      light

# Ćwiczenie 11

Dany jest obiekt Data Frame z poprzedniego zadania. Dokonaj kodowania kategorii wagowych za pomocą funkcji pd.get_dummies().

In [ ]:
df = pd.get_dummies(df)
df

weight  weight_cut_light  weight_cut_medium  weight_cut_heavy
0    75.0                 1                  0                 0
1    78.5                 0                  1                 0
2    85.0                 0                  0                 1
3    91.0                 0                  0                 1
4    84.5                 0                  0                 1
5    83.0                 0                  0                 1
6    68.0                 1                  0                 0

# Ćwiczenie 12

Dany jest obiekt Data Frame. Do obiektu przypisz nową kolumnę o nazwie "number", która przyjmie liczbę elementów listy w kolumnie "currency".

In [ ]:
# Utworzenie obiektu Data Frame:
dane = {'currency': [['PLN', 'USD'], ['EUR', 'USD', 'PLN', 'CAD'], ['GBP'], ['JPY', 'CZK', 'HUF'], []]}
df = pd.DataFrame(dane)

# Utworzenie nowej kategorii
# Liczbę elementów w poszczególnyvh komórkach określimy za pomocą apply(len):
df["number"] = df['currency'].apply(len)
df

currency  number
0            [PLN, USD]       2
1  [EUR, USD, PLN, CAD]       4
2                 [GBP]       1
3       [JPY, CZK, HUF]       3
4                    []       0

# Ćwiczenie 13

Dany jest obiekt Data Frame (jak w poprzednim zadaniu). Dodaj nową kolumnę o nazwie "PLN_flag", która zwróci wartość 1, jeśli wśród walud znajdzie się złoty lub 0, jeśli nie będzie go tam.

In [ ]:
# Składnia: .apply(lambda obszar, w którym szukamy: 1 jeśli 'PLN' jest w tym obszarze jeśli nie to 0)
df['PLN_flag'] = df['currency'].apply(lambda item: 1 if 'PLN' in item else 0)
df

currency  number  PLN_flag
0            [PLN, USD]       2         1
1  [EUR, USD, PLN, CAD]       4         1
2                 [GBP]       1         0
3       [JPY, CZK, HUF]       3         0
4                    []       0         0

# Ćwiczenie 14

Dany jest zestaw danych (poniżej). Podziel wartości kolumny względem znaku "#" używając pd.Series.str.split() z argumentem "expand = True". Otrzymasz cztery kolumny. Pierwsza będzie zawierała puste stringi. Usuń ją. Następnie przypisz nazwy kolumn: 'hashtag1', 'hashtag2', 'hashtag3'.

In [ ]:
# Dane:
data={'hashtags': ['#good#vibes', '#hot#summer#holiday', '#street#food', '#workout']}

# Tworzenie DataFrame:
df = pd.DataFrame(data)

# Dzielenie wyrazów na hashtagi:
df = df['hashtags'].str.split('#', expand = True)

# Usuwanie pierwszej kolumny:
df = df.drop(columns = [0])

# Przypisz kolumnom nazwy:
df.columns = ['hashtag 1', 'hashtag 2', 'hashtag 3']
df

hashtag 1 hashtag 2 hashtag 3
0      good     vibes      None
1       hot    summer   holiday
2    street      food      None
3   workout      None      None

# Ćwiczenie 15

Do obiektu df z poprzedniego zadania dopisz kolumnę 'missing', która policzy puste pola w każdym wierszu.# 

In [ ]:
# Funkcja, która liczy wszystkie puste kolumny w wierszu. Dodanie nowej kolumny z wynikiem liczenia.
df['missing'] = df.isnull().sum(axis = 1)
df

hashtag 1 hashtag 2 hashtag 3  missing
0      good     vibes      None        1
1       hot    summer   holiday        0
2    street      food      None        1
3   workout      None      None        2

# Ćwiczenie 16

Dany jest zestaw danych (poniżej). Przekształć wartości w kolumnach na liczby (int).

In [ ]:
# Dane:
df = pd.DataFrame(data={'investments': ['100_000_000', '100_000', '30_000_000', '100_500_000']})

# Przekształcenie. Zamieniamy znak '_' na '' i zmieniamy format na int:
df['investments'] = df['investments'].str.replace("-", "").astype(int)
df

investments
0    100000000
1       100000
2     30000000
3    100500000

# Ćwiczenie 17

Załaduj zbiór danych IRIS do zmiennej data, wykorzystując funkcję load_iris() z pakietu scikit-learn. Wyświetl wszystkie klucze zmiennej data.

In [ ]:
# Pobranie danych:
data = load_iris()

# Wyświetlenie kluczy:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

# Ćwiczenie 18

Wyświetl nazwy zmiennych 'feature_names' oraz nazwy klas 'target_names' w załadowanym zestawie danych.


In [ ]:
print(data["feature_names"])
print(data["target_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


# Ćwiczenie 19

Do zmiennej "data_raw" przypisano załadowane dane z setu "IRIS". Do zmiennej "data" przypisz dane ze zbioru IRIS (klucz: "data"). Do zmiennej "target" przypisz wartości zmiennej docelowej ("target") zw zbioru IRIS.

In [ ]:
# Załadowanie danych:
data_raw = load_iris()

# Zdefiniowanie zmiennych:
data = data_raw["data"]
target = data_raw["target"]

# Rozmiaty arrays z danymi:
print(data.shape)
print(target.shape)

(150, 4)
(150,)


# Ćwiczenie 20

Z wyodrębnionych w poprzednim ćwiczeniu tablic: "data" oraz "target", podziel je na zbiory uczące i testowe: data_uczący, data_testowy, target_uczący, target_testowy. (Za pomocą funkcji train_test_split()). Ustal rozmiar zbiotu testowego na 30 %. Wyświetl rozmiary zbiorów.

In [ ]:
# Podział na zbiory uczący i testowy:
data_uczący, data_testowy, target_uczący, target_testowy = train_test_split(data, target, test_size = 0.3, random_state = 2020)

# Rozmiary zbiorów:
print("Rozmiary zbiorów: data_uczący: ", data_uczący.shape,
      ", data_testowy: ", data_testowy.shape, "\n"
      "target_uczący: ", target_uczący.shape,
      ", target_testowy: ", target_testowy.shape)

Rozmiary zbiorów: data_uczący:  (105, 4) , data_testowy:  (45, 4) 
target_uczący:  (105,) , target_testowy:  (45,)


# Ćwiczenie 21

Z wykorzystaniem zbiorów z poprzedniego zadania, zbuduj model regresji logistycznej (ustaw jako argument "max_iter" = 1000), wykorzystując pakiet scikit-learn.

Model wytrenuj na danych uczących i sprawdź na danych testowych. W odpowiedzi pokaż dokładność modelu na zbiorze testowym. Powinno wyjść 0.9333.

In [ ]:
# Budujemy model do przewidywania gatunku irysa na podstawie wymiarów liścia i łodygi.
# Definiowanie modelu regresji logistycznej:
model = LogisticRegression(max_iter = 1000)         # reszta parametrów pozostaje domyślna

# Wytrenowanie modelu na zbiorze uczącym:
model.fit(data_uczący, target_uczący)

# Zastosowanie modelu na zbiorze testowym i wyznaczenie współczynnika accuracy:
acc = model.score(data_testowy, target_testowy)
print(round(acc, 4))

0.9111


# Ćwiczenie 22

Zbudowałeś i wytrenowałeś model regresji logistycznej. Teraz za pomocą tego modelu, dokonaj predykcji danych testowych i przypisz je do zmiennej "target_pred". Wyświetl tę zmienną.

In [ ]:
# Nasz model teraz przewidzi gatunek kwiatów na podstawie dantych i tego, czego nauczył się na zbiorach uczących.
# Predykcja wartości paramterów "target"
target_pred = model.predict(data_testowy)
print(target_testowy)
print(target_pred)

for i in target_pred:
  print(target_pred[i] == target_testowy[i], end = " ")

# Wynika z tego, że nasz algorytm nie pomylił się ani razu przewidując gatunek irysa :-)

[2 0 1 1 1 2 2 1 0 0 2 2 0 2 2 0 1 1 2 0 0 2 1 0 2 1 1 1 0 0 2 0 0 0 2 0 0
 1 0 2 0 2 1 0 1]
[2 0 1 1 1 1 2 1 0 0 2 1 0 2 2 0 1 1 2 0 0 2 2 0 2 1 1 2 0 0 2 0 0 0 2 0 0
 1 0 2 0 2 1 0 1]
True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True 

# Ćwiczenie 23

Utwórz macierz pomyłek (confusion matrix) zastosowanego modelu.

In [ ]:
# Macierz pomyłek:
confusion_matrix(target_testowy, target_pred)

array([[18,  0,  0],
       [ 0, 11,  2],
       [ 0,  2, 12]])

# Ćwiczenie 24

Wyświetl raport klasyfikacji tego modelu wykorzystując funkcję classification_report() z pakietu scikit-learn.

In [ ]:
# Wyświetlenie raportu:
classification_report(target_testowy, target_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        18\n           1       0.85      0.85      0.85        13\n           2       0.86      0.86      0.86        14\n\n    accuracy                           0.91        45\n   macro avg       0.90      0.90      0.90        45\nweighted avg       0.91      0.91      0.91        45\n'

# Ćwiczenie 25

Dany jest obiekt Data Frame (poniżej). Wykorzystując klasę "LabelEncoder" z pakietu scikit-learn dokonaj kodowania 0-1 kolumny "bought". Przypisz zmiany do zmiennej df.

In [ ]:
# Dane:
data = {'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']}
df = pd.DataFrame(data)

# Kategorie kolumn:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')
df['weight'] = df['weight'].astype('float')

# Kodowanie kategorii w zmiennej "bought"
encoder = LabelEncoder()
df["bought"] = encoder.fit_transform(df["bought"])

df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

# Ćwiczenie 26

Znowusz mamy obiekt Data Frame. Wykorzystując klasę "OneHotEncoder" z pakietu "scikit-learn" dokonaj kodowania 0-1 kolumny "size" (Ustaw argument "sparse = False"). Nie zapisuj tego do df. Wydrukuj także otrzymane kategorie przy kodowaniu kolumny "size".

In [ ]:
# Utworzenie enkodera:
ohe = OneHotEncoder(sparse = False)

# Zastosowanie enkodera:
x = ohe.fit_transform(df[["size"]])
print(x)
print(ohe.categories_)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[array(['L', 'M', 'XL'], dtype=object)]


# ćwiczenie 27

Załaduj dane "load_breast_cancer()" z pakietu scikit-learn do zmiennej "raw_data". Następnie wyświetl informacje o tym zbiorze (zawartość klucza "DESCR").

In [ ]:
# Pobranie danych:
raw_data = load_breast_cancer()
raw_data["DESCR"]

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance,

# Ćwiczenie 28

Z załadowanych danych "breast cancer" wyciągnij kilka danych. Do zmiennej "data" przypisztablicę "numpy" z danymi ze zmiennej "raw_data" (klucz "data") oraz do zmiennej "target" ze zmienną docelową "target".

In [ ]:
data = raw_data["data"]
target = raw_data["target"]

print(data[:3])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]]


# Ćwiczenie 29

Połącz dwie tablice z poprzedniego ćwiczenia w jedną o nazwie "all_data" i wyświetl trzy pierwsze wiersze.

In [ ]:
# Funkcja np.c_[] pozwoli połączyć 2 arrays w jednen:
all_data = np.c_[data, target]
print(all_data[:3])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01 0.000e+00]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02 0.000e+00]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02 0.000e+00]]


# Ćwiczenie 30

Z tablicy "all_data" utwórz obiekt Data Frame, nadając odpowiednio nazwy kolumn (klucz: "feature_names") obiektu "raw_data" + nazwa zmiennej docelowej jako "target".

In [ ]:
# Utworzenie obiektu Data Frame z zadanymi nazwami kolumn:
all_data2 = pd.DataFrame(data = all_data, columns = list(raw_data["feature_names"]) + ["target"])
all_data2.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890     0.0
1        20.57         17.77  ...                  0.08902     0.0
2        19.69         21.25  ...                  0.08758     0.0
3        11.42         20.38  ...                  0.17300     0.0
4        20.29         14.34  ...                  0.07678     0.0

[5 rows x 31 columns]

# Ćwiczenie 31

Wykorzystując funkcję "train_test_split()" podziel te dane na zbiór uczący i testowy (data oraz target). Ustaw rozmiar zbioru testowego na 25 % oraz ziarno losowości na 40. Wyświetl rozmiary zbiorów:


In [ ]:
# Dzielenie na zbiory: uczący i testowy:
data_uczący, data_testowy, target_uczący, target_testowy = train_test_split(data, target, test_size = 0.25, random_state = 40)

# Wielkości zbiorów:
print("data_uczący: ", data_uczący.shape, "\n",
      "data_testowy: ", data_testowy.shape, "\n",
      "target_uczący: ", target_uczący.shape, "\n",
      "target_testowy: ", target_testowy.shape)

data_uczący:  (426, 30) 
 data_testowy:  (143, 30) 
 target_uczący:  (426,) 
 target_testowy:  (143,)


# Ćwiczenie 32

Sprawdź procentowy rozkład wartości zmiennych: "target", "target_uczący", "target_testowy".

In [ ]:
# Wartości unikalne w zbiorach:
un_target = np.unique(target, return_counts = True)[1] / len(target)
un_target_u = np.unique(target_uczący, return_counts = True)[1] / len(target_uczący)
un_target_t = np.unique(target_testowy, return_counts = True)[1] / len(target_testowy)

print(un_target, "\n", un_target_u, "\n", un_target_t)

[0.37258348 0.62741652] 
 [0.39201878 0.60798122] 
 [0.31468531 0.68531469]


# Ćwiczenie 33

Podziel dane data, target na zbiory: uczący i testowy, tak aby zachować procentowy rozkład wartości w tablicach: "target_uczący" i "target_testowy", taki jak w tablicy "target".

In [ ]:
# To będzie wyglądało niemal tak samo, jak dwa zadania wcześniej, z małą różnicą: dodamy do funkcji jeszcze jeden argument.
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state = 40, stratify = target)

# Sprawdzamy:
um_target = np.unique(target, return_counts = True)[1] / len(target)
um_y_train = np.unique(y_train, return_counts = True)[1] / len(y_train)
um_y_test = np.unique(y_test, return_counts = True)[1] / len(y_test)

print(um_target, "\n", um_y_train, '\n', um_y_test)

[0.37258348 0.62741652] 
 [0.37323944 0.62676056] 
 [0.37062937 0.62937063]


# Ćwiczenie 34

Dany jest zestaw danych (poniżej). Pierwsza kolumna to zmienna objaśniająca a druga - zmienna objaśniana. Wykorzystując równanie normalne oraz pakiet numpy, wyznacz równanie linii trendy (regresja liniowa).

In [ ]:
# Dane:
df = pd.DataFrame({'years': [1, 2, 3, 4, 5, 6],
                   'salary': [4000, 4250, 4500, 4750, 5000, 5250]})

# współrzędne punktow:
X1 = df['years'].values
Y = df['salary'].values

# Przekształcenie macierzy X1:
m = len(df)
X1 = X1.reshape(m, 1)

# Wyznaczenie macierzy X:
bias = np.ones((m, 1))
X = np.append(bias, X1, axis = 1)

# Wyznaczenie wartości współczynnika przesunięcia i współczynnika kierunkowego:
coefs = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))

# Odpowiedź:
print(f"Linear regression: {coefs[0]:.2f} + {coefs[1]:.2f}x")

Linear regression: 3750.00 + 250.00x


# Ćwiczenie 35

Znów ten sam Data Frame i to samo zadanie. Tym razem rozwal je wykorzystując funkcję "LinearRegression" w pakiecie scikit-learn.

In [ ]:
# Tworzenie modelu:
model = LinearRegression()

# Trenowanie modelu: iksy i igreki:
model.fit(df[['years']], df[['salary']])

# Odpowiedź:
print(f'Linear regression: {model.intercept_[0]:.2f} + {model.coef_[0][0]:.2f}x')

Linear regression: 3750.00 + 250.00x


# Ćwiczenie 36

Wczytaj dane do obiektu Data Frame. Następnie, w oparciu o zmienną 'variable', zbuduj model grgresji liniowej pozwalający przewidywać wartości zmiennej docelowej 'target'. Wykorzystaj w tym celu pakiet scikit-learn oraz funkcję LinearRegression.

In [ ]:
# Wczytanie danych:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/data.csv', delimiter = ',')
data

# Tym razem nie będzie dzielenia danych na zbiory. Wykorzystamy do nauki wszysko:
x = data[['variable']]
y = data[['target']]

# Zdefiniuj model:
model = LinearRegression()

# Uczenie modelu:
model.fit(x, y)

# Sprawdzenie modelu:
result = model.score(x, y)
print(round(float(result), 4))

0.5532


# Ćwiczenie 37

Wczytaj dane z pliku "data2.csv". Dokonaj ekstrakcji wielomianowych za zmiennej 'var1' stopnia drugiego. Otrzymane cechy w postaci tablicy numpy wyświetl.

In [ ]:
# wczytaj dane:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/data2.csv', delimiter = ',')
data

# Ekstrakcja:
poly = PolynomialFeatures(degree = 2)
df_poly = poly.fit_transform(data)
df_poly

array([[ 1.        , -0.54203446,  0.29380135],
       [ 1.        ,  0.52861971,  0.2794388 ],
       [ 1.        ,  0.62514332,  0.39080417],
       [ 1.        ,  0.19397775,  0.03762737],
       [ 1.        , -0.80025878,  0.64041412],
       [ 1.        , -0.30353167,  0.09213148],
       [ 1.        ,  1.08617991,  1.17978679],
       [ 1.        , -1.1601817 ,  1.34602158],
       [ 1.        ,  1.03831416,  1.07809629],
       [ 1.        , -0.81530272,  0.66471852],
       [ 1.        ,  0.41601746,  0.17307052],
       [ 1.        ,  1.29711284,  1.68250171],
       [ 1.        , -0.43286591,  0.1873729 ],
       [ 1.        ,  1.05874434,  1.12093957],
       [ 1.        ,  1.13877614,  1.2968111 ],
       [ 1.        ,  0.99991287,  0.99982575],
       [ 1.        ,  0.108967  ,  0.01187381],
       [ 1.        , -0.39014048,  0.15220959],
       [ 1.        , -0.70064547,  0.49090407],
       [ 1.        ,  0.69831212,  0.48763982],
       [ 1.        ,  0.75157138,  0.564

# Ćwiczenie 38

Wczytaj plik 'data3.csv'. Następnie dokonaj ekstrakcji cech wielomianowych ze zmiennych 'var1' i 'var2' stopnia trzeciego. Otrzymane cechy wyświetl.

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/data3.csv', delimiter = ',')
data

# Ustawienie parametrów macierzy: zaokrąglenie, wielkość linijki:
np.set_printoptions(suppress = True, precision = 3, linewidth = 150)

# Ekstrakcja:
poly = PolynomialFeatures(degree = 3)
df_poly = poly.fit_transform(data)
df_poly

array([[  1.   ,  -0.016,   0.589,   0.   ,  -0.01 ,   0.347,  -0.   ,   0.   ,  -0.006,   0.204],
       [  1.   ,   0.754,   0.076,   0.569,   0.058,   0.006,   0.429,   0.043,   0.004,   0.   ],
       [  1.   ,  -1.157,  -1.465,   1.338,   1.695,   2.146,  -1.548,  -1.96 ,  -2.482,  -3.143],
       [  1.   ,   0.177,  -0.175,   0.031,  -0.031,   0.031,   0.006,  -0.006,   0.005,  -0.005],
       [  1.   ,  -2.502,   1.536,   6.258,  -3.843,   2.36 , -15.656,   9.615,  -5.905,   3.626],
       [  1.   ,   0.631,   0.537,   0.398,   0.339,   0.288,   0.251,   0.214,   0.182,   0.155],
       [  1.   ,   0.239,   0.227,   0.057,   0.054,   0.051,   0.014,   0.013,   0.012,   0.012],
       [  1.   ,   1.062,   0.598,   1.127,   0.635,   0.358,   1.197,   0.675,   0.38 ,   0.214],
       [  1.   ,  -0.837,  -0.328,   0.7  ,   0.275,   0.108,  -0.586,  -0.23 ,  -0.09 ,  -0.035],
       [  1.   ,   0.567,  -0.313,   0.321,  -0.178,   0.098,   0.182,  -0.101,   0.056,  -0.031],
       [  

# Ćwiczenie 39

Plik 'Predictions.csv' zawiera predykcje pewnego modelu regresji:
* zmienna y_true opisuje rzeczywiste wartości
* zmienna y_pred opisuje wartości przewidziane przez model.

Wczytaj ten plik do Data Frame i stwórz funkcję o nazwie 'mean_absolute_error()' obliczającą średni błąd bezwzględny predykcji. Oblicz wartość MAE dla tego modelu.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/Predictions.csv', delimiter = ',')
df

# Średni bezwzględny błąd predykcji - stworzenie funkcji:
def mean_absolute_error(y_true, y_pred):
  MAE = abs(y_true - y_pred).sum() / len(y_true)
  return round(MAE, 4)

# Obliczenie MAE:
y_true = df['y_true']
y_pred = df['y_pred']

mean_absolute_error(y_true, y_pred)

6.7918

# Ćwiczenie 40

Z tego samego zestawu danych, oblicz błąd średniokwadratowy predykcji. Stwórz funkcję i ją wykorzystaj do obliczeń.

In [ ]:
df

# Stworzenie funkcji:
def mean_squared_error(a, b):
  MSE = ((a - b)**2).sum() / len(a)
  return round(MSE, 4)

# Obliczenia:
mean_squared_error(y_true, y_pred)

74.9471

# Ćwiczenie 41

Stwórz funkcję Sigmoid i policz jej wartość dla zmiennych 'var1'. Przypisz wynik do kolumny o nazwie 'var1_sigmoid'.

In [ ]:
# Dane - stworzenie Data Frame:
df = pd.DataFrame(data = np.random.randn(10), columns = ['var1'])
# Stworzenie funkcji SIGMOID:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
  
# Użycie funkcji:
df['var1_sigmoid'] = sigmoid(df['var1'])
df

var1  var1_sigmoid
0  1.465649      0.812395
1 -0.225776      0.443794
2  0.067528      0.516876
3 -1.424748      0.193918
4 -0.544383      0.367169
5  0.110923      0.527702
6 -1.150994      0.240308
7  0.375698      0.592835
8 -0.600639      0.354198
9 -0.291694      0.427589

# Ćwiczenie 42

Wczytaj plik 'data4.csv'. Następnie wykorzystując funkcję StandardScaler() z pakietu scikit-learn dokonaj standaryzacji kolumn. Wyświetl wystandaryzowany Data Frame.

In [ ]:
# Wczytanie danych do standaryzacji:
np.set_printoptions(precision = 4, suppress = True)
dane = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/data4.csv', delimiter = ',')
print(dane)

# Utworzenie skalera:
scaler = StandardScaler()

# Wytrenowanie skalera:
scaler.fit(dane)

# Dane przeskalowane:
dane_scalled = scaler.fit_transform(dane)
print(dane_scalled[:5])

      var1   var2    var3    var4     var5
0    12.47  18.60   81.09   481.9  0.09965
1    18.94  21.31  123.60  1130.0  0.09009
2    15.46  19.48  101.70   748.9  0.10920
3    12.40  17.68   81.47   467.8  0.10540
4    11.54  14.44   74.65   402.9  0.09984
..     ...    ...     ...     ...      ...
138  14.64  15.24   95.77   651.9  0.11320
139  14.45  20.22   94.49   642.7  0.09872
140  11.04  16.83   70.92   373.2  0.10770
141  19.81  22.15  130.00  1260.0  0.09831
142  10.26  12.22   65.75   321.6  0.09996

[143 rows x 5 columns]
[[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
 [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
 [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
 [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
 [-0.7449 -1.1397 -0.7236 -0.745   0.0771]]


# Ćwiczenie 43

Wczytaj pliki 'X_train.csv' oraz 'X_test.csv'. do obiektów Data Frame. Następnie, wykorzystując funkcję StandardScaller() z pakietu scikit-learn dokonaj standaryzacji danych. Dane dopasuj na zbiorze uczącym X_train.

In [ ]:
# Wczytanie danych:
X_train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/X_train.csv', delimiter = ',')
X_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Pliki pomocnicze/X_test.csv', delimiter = ',')

# Utworzenie skalera:
scaler = StandardScaler()

# Wytrenowanie skalera:
scaler.fit(X_train)

# Użycie skalera:
X_train_sc = scaler.transform(X_train)
X_test_sc = scaler.transform(X_test)

print(X_train_sc[:5], "\n\n", X_test_sc[:5])


NameError: ignored

# Ćwiczenie 44

Stwórz funkcję "entropy()" z wykorzystaniem pakietu numpy. Następnie, za pomocą tej funkcji, wylicz zawartość trzeciej kolumny tabeli o nazwie 'entropy'.

In [ ]:
# Steorzenie funkcji entropy():
def entropy(x):
  return np.round(-np.sum(x * np.log2(x)), 4)

# Dane do analizy:
data = pd.DataFrame({'val_1': np.arange(0.09, 0.99, 0.1), 'val_2': np.arange(0.99, 0.09, -0.1)})
data['entropy'] = entropy([data['val_1'] * data['val_2']])
data

val_1  val_2  entropy
0   0.09   0.99   4.2065
1   0.19   0.89   4.2065
2   0.29   0.79   4.2065
3   0.39   0.69   4.2065
4   0.49   0.59   4.2065
5   0.59   0.49   4.2065
6   0.69   0.39   4.2065
7   0.79   0.29   4.2065
8   0.89   0.19   4.2065

# Ćwiczenie 45

W pliku znajdują się wyniki predykcji na podstawie pewnego modelu klasyfikacji wieloklasowej (3 klasy). Kolumna y_true opisuje rzeczywiste wartoście, zaś kolumna y_pred wartości przewidziane przez model. Wykorzystując funkcję accuracy_score() z pakietu scikit-learn policz dokładność tego modelu.

In [7]:
# Dane:
data = pd.DataFrame({'y_true': [1,0,1,2,1,0,1,1,0,1,0,1,1,0,2,1,1,2,2,1,0,1,1,0,2,1,1,2],
                    'y_pred': [0,0,1,2,1,1,1,1,0,2,0,1,1,0,2,2,1,0,2,1,0,1,1,0,1,1,1,2]})
data

# Współczynnik dokładności:
acc = accuracy_score(data['y_true'], data['y_pred'])
print(round(float(acc), 4))

NameError: ignored