<a href="https://colab.research.google.com/github/RobSpiewakowski/nauka-data-science/blob/main/skrypty-colab/%C4%86wiczenia_skalary%2C_wektory_i_macierze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def kreski():
  print("---------------------")

In [ ]:
# Definiowanie zmiennej skalarnej:
a = 5
b = np.array(6)

# Definiowanie wektora:
c = np.array([1, 5, 10, 15, -25])

# Definiowanie macierzy:
d = np.array([[1, 6, 9], [-9, 2, 0], [-9, 12, -4]])

print(a, type(a))
kreski()
print(b, type(b))
kreski()
print(c, type(c))
kreski()
print(d, type(d))

5 <class 'int'>
---------------------
6 <class 'numpy.ndarray'>
---------------------
[  1   5  10  15 -25] <class 'numpy.ndarray'>
---------------------
[[ 1  6  9]
 [-9  2  0]
 [-9 12 -4]] <class 'numpy.ndarray'>


In [ ]:
# Sprawdzanie rozmiaru obiektu:
print(b.shape)
kreski()
print(c.shape)
kreski()
print(d.shape)

()
---------------------
(5,)
---------------------
(3, 3)


In [ ]:
# Transpozycja wektora / macierzy:
c.reshape(5,1)

array([[  1],
       [  5],
       [ 10],
       [ 15],
       [-25]])

In [ ]:
c.reshape(1,5)

array([[  1,   5,  10,  15, -25]])

In [ ]:
# Operacje na obiektach - dodawanie macierzy:
m1 = np.array([[1, 6, 8], [-9, 2, 7]])
m2 = np.array([[6, 4, -4], [-9, 0, 2]])

m3 = m1 + m2
print("dodawanie macierzy: \n", m3)
kreski()

# Operacje na obiektach - odejmowanie macierzy:
m4 = m1 - m2
print("odejmowanie macierzy: \n", m4)
kreski()

# Operacje na obiektach - mnożenie macierzy:
# Warunkiem powodzenia mnożenia macierzy jest, żeby macierz 1 musi mieć tyle wierszy ile kolumn ma macierz 2:
m5 = np.dot(m1.reshape(3,2), m2)
print("mnożenie macierzy 3x2 i 2x3: \n", m5)
kreski()
# Mnożenie macierzy NIE jest przemienne!
m6 = np.dot(m2, m1.reshape(3, 2))
print("mnożenie macierzy 2x3 i 3x2: \n", m6)
kreski()

# Operacje na obiektach - dzielenie tablicowe macierzy:
# Dzielenie elementu macierzy a przez odpowiadający jej element macierzy b. Macierze muszą mieć te same wymiary:
m7 = np.divide(m2, m1)
print("Dzielenie tablicowe macierzy: \n", m7)

dodawanie macierzy: 
 [[  7  10   4]
 [-18   2   9]]
---------------------
odejmowanie macierzy: 
 [[-5  2 12]
 [ 0  2  5]]
---------------------
mnożenie macierzy 3x2 i 2x3: 
 [[-48   4   8]
 [129  32 -50]
 [-51   8   6]]
---------------------
mnożenie macierzy 2x3 i 3x2: 
 [[ 30 -28]
 [ -5 -40]]
---------------------
Dzielenie tablicowe macierzy: 
 [[ 6.          0.66666667 -0.5       ]
 [ 1.          0.          0.28571429]]


In [ ]:
# Operacje na wektorach - dodawanie wektorów:
w1 = np.array([1, 2, 3, 4])
w2 = np.array([5, 6, 7, 8])

w3 = w1 + w2
print("dodawanie wektorów: \n", w3)
kreski()

# Operacje na wektorach - odejmowanie wektorów:
w4 = w2 - w1
print("odejmowanie wektorów: \n", w4)
kreski()

# Operacje na wektorach - mnożenie skalarne:
w5 = np.dot(w1, w2)
print("iloczyn skalarny wektorów: \n", w5)
kreski()

# Operacje na wektorach - mnożenie przez skalar:
w6 = 2*w1
print("mnożenie wektora przez liczbę: \n", w6)
kreski()

dodawanie wektorów: 
 [ 6  8 10 12]
---------------------
odejmowanie wektorów: 
 [4 4 4 4]
---------------------
iloczyn skalarny wektorów: 
 70
---------------------
mnożenie wektora przez liczbę: 
 [2 4 6 8]
---------------------


In [ ]:
# Operacje na wektorach, macierzach i skalarach:
# Dodawanie skalara do macierzy:
x1 = m1 + 3
print("dodawanie liczby do macierzy: \n", x1)
kreski()

# Dodawanie skalara do wektowa:
x2 = w1 + 5
print("dodawanie liczby do wektora: \n", x2)
kreski()

dodawanie liczby do macierzy: 
 [[ 4  9 11]
 [-6  5 10]]
---------------------
dodawanie liczby do wektora: 
 [6 7 8 9]
---------------------


In [ ]:
# Transpozycja macierzy i wektorów:
x3 = m2.T
print("macierz m2 transponowana: \n", x3)
kreski()

macierz m2 transponowana: 
 [[ 6 -9]
 [ 4  0]
 [-4  2]]
---------------------
